### ISSUE TITLE
Not received foreground notification info on OnMessageReceive

### ISSUE THREAD

**Issue by testanddeploy** [dpa99c/cordova-plugin-firebasex#52]
# Bug report

No notification received on OnMessageReceived when app is in foreground Mode with a notification sended from Firebase console.

When the app is in background mode the notification arrives to system tray and then if i click to it the info that arrives to OnMessageReceived is this:

```
collapse_key: "com.mybundleid.app"
from: "679237267662"
google.delivered_priority: "high"
google.message_id: "0:1563868372948653%a793bb1ea793bb1e"
google.original_priority: "high"
google.sent_time: 1563868372756
google.ttl: 2419200
messageType: "notification"
tap: "background"
```
No info about title, body.. arrives.

**Expected behavior:**
Notification info arrives to OnMessageReceived from both modes, foreground and background(tapped)

**Environment information**
```
Ionic:

   ionic (Ionic CLI)  : 4.12.0 (/usr/local/lib/node_modules/ionic)
   Ionic Framework    : ionic-angular 3.9.6
   @ionic/app-scripts : 3.2.3

Cordova:

   cordova (Cordova CLI) : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms     : android 8.0.0, ios 5.0.1
   Cordova Plugins       : cordova-plugin-ionic-webview 1.2.1, (and 22 other plugins)

System:

   Android SDK Tools : 26.1.1 (/Users/myuser/Library/Android/sdk)
   ios-deploy        : 1.9.2
   ios-sim           : 8.0.1
   NodeJS            : v9.9.0 (/usr/local/bin/node)
   npm               : 5.7.1
   OS                : macOS Mojave
   Xcode             : Xcode 10.2.1 Build version 10E1001
```

- Device details
    - Samsung device
- OS details
    - Android 7.0	
	

**cordova-plugin-firebasex 6.0.0
cordova-plugin-androidx 1.0.2
cordova-plugin-androidx-adapter 1.1.0**

**Related code:**
```
...
declare const window: any;
...

    getNotificationRecived() {
       console.log('before')
        window.FirebasePlugin.onMessageReceived(function(message) {
            console.dir(message) // above info showed
            console.dir(message.title) // undefined
            console.dir(message.notification.title) // error
            console.log("Message type: " + message.messageType); // notification
            if (message.messageType === "notification"){
                console.log("Notification message received");
                if(message.tap){
                    console.log("Tapped in " + message.tap);
                }
            }
            //console.dir(notification);
        },function(error)  {
            console.error(error);
        });
```

More info:

I have already tested sending a test notification and a full notification from firebase console. The behaviour is the same.

Thanks for your work

**Comment by dpa99c** [comment]
Thanks for reporting - I'll have a look into this later

**Comment by dpa99c** [comment]
I've published this fix in `cordova-plugin-firebasex@6.0.1`

**Comment by tusharvikky** [comment]
I tried the same with latest 6.0.1. Still foreground push not working.

**Comment by dpa99c** [comment]
[notification.json](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/messages/notification.json) sent to [example project app](https://github.com/dpa99c/cordova-plugin-firebasex-test) using `cordova-plugin-firebasex@6.0.1` while in foreground:

![Screenshot_20190724-091302](https://user-images.githubusercontent.com/2345062/61776782-a184bd80-adf3-11e9-82c3-9c08109cf1c9.png)

**Comment by testanddeploy** [comment]
Now with 6.0.1:

While foreground the notification arrives with the info:

**body: "555"**
collapse_key: "com.bundle.app"
from: "679237267662"
id: "0:1563958960304468%a793bb1ea793bb1e"
messageType: "notification"
sent_time: "1563958960293"
show_notification: "false"
**title: "55"**
ttl: "2419200"

However if the app is background(killed and minimized) and tap it the notification arrives with:

collapse_key: "com.bundle.app"
from: "679237267662"
google.delivered_priority: "high"
google.message_id: "0:1563959031769194%a793bb1ea793bb1e"
google.original_priority: "high"
google.sent_time: 1563959031764
google.ttl: 2419200
messageType: "notification"
**tap: "background"**

**Comment by testanddeploy** [comment]
If I send a push notification via postman to :

`https://fcm.googleapis.com/fcm/send`

With this body (your notification.json example):

```
{
  "to":"MY_DEVICE_TOKEN", 
  "name": "notification",
  "notification": {
    "body": "Notification with default settings",
    "title": "Default Notification"
  },
  "android": {
    "collapse_key": "a",
    "priority": "normal",
    "ttl": "3600s",
    "notification": {
      "channel_id": "fcm_default_channel",
      "sound": "default",
      "color": "#4290b7"

    }
  },
  "apns": {
    "payload": {
      "aps": {
        "badge": 1,
        "sound": "default"
      }
    }
  },
  "data": {
    "notification_foreground": "true",
    "key_1": "Data for key one"
  }
}
```
The app closes and the LogCat shows this error:

```
07-24 14:27:23.488 9092-9886/com.bundle.app E/AndroidRuntime: FATAL EXCEPTION: Firebase-FirebasePluginMessagingService
    Process: com.bundle.app, PID: 9092
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
        at org.apache.cordova.firebase.FirebasePluginMessagingService.sendMessage(FirebasePluginMessagingService.java:206)
        at org.apache.cordova.firebase.FirebasePluginMessagingService.onMessageReceived(FirebasePluginMessagingService.java:154)
        at com.google.firebase.messaging.FirebaseMessagingService.zzd(Unknown Source)
        at com.google.firebase.iid.zzb.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:761)
07-24 14:27:24.190 9092-9170/com.bundle.app E/ConnectivityManager.CallbackHandler: callback not found for RELEASED message
```

**Comment by dpa99c** [comment]
> One question, do you receive reports if this issue is clossed? Or I have to open new issue?

I still get emails.

**Comment by dpa99c** [comment]
> If I send a push notification via postman to : https://fcm.googleapis.com/fcm/send

This is the legacy API - `notification.json` is formatted for the [v1 API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send): `https://fcm.googleapis.com/v1/`

But yes, it shouldn't cause an app crash - I will fix that.

**Comment by dpa99c** [comment]
I've published `cordova-plugin-firebasex@6.0.2` which improves the Android implementation: 
better exception handling e.g. sending malformed notification message should no longer cause an app crash but will log error to Crashlytics/logcat/Webview.

Note that if the app is not running when the notification message arrives on Android, when you tap the system notification to launch the app, the full notification message payload (e.g. title & body) is not available in the Intent, therefore the plugin cannot forward this on to `onMessageReceived()`.

I've updated [the documentation](https://github.com/dpa99c/cordova-plugin-firebasex#android-background-notifications) to make this explicitly clear.

**Comment by M0NsTeRRR** [comment]
Hello,

First of all thanks for your work, pleasure to work with your updated plugin :)

You forget to update the documentation too, because this `tap=foreground|background` should be this now `tap=background`

**Comment by dpa99c** [comment]
@M0NsTeRRR The documentation is correct: `|` is the logical OR operator so is conventionally used to list multiple possible values, i.e.

`tap=foreground|background` => `tap=foreground` OR `tap=background`

**Comment by testanddeploy** [comment]
Hi, in the documentation is not explicit, on iOS notifications the `notification_foreground` takes effect?
On iOS I am not get the notification on system tray if app is in foreground.

> > If I send a push notification via postman to : https://fcm.googleapis.com/fcm/send
> 
> This is the legacy API - `notification.json` is formatted for the [v1 API](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages/send): `https://fcm.googleapis.com/v1/`

I am trying via Postman with this url but get a 404 error
`https://fcm.googleapis.com/v1/projects/myproject-hash/messages:send`

Is the url correct?

**Comment by dpa99c** [comment]
It looks correct, however I have not interacted directly with the v1 FCM API via HTTP, but instead use the [google-auth-library](https://github.com/googleapis/google-auth-library-nodejs) in a NodeJS environment to send the messages, as the [sendMessage script](https://github.com/dpa99c/cordova-plugin-firebasex-test/blob/master/scripts/sendMessage.js) does in the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test)

**Comment by testanddeploy** [comment]
about foreground notifications on ios?

**Comment by tusharvikky** [comment]
I'm not sure what changed. After two days investing for foreground notification to work. I rolled back to v6.0.0 and the foreground works fine. However, same doesn't work on v6.0.1 as well as on v6.0.2. I have a ionic 4 project w/ angular. 

I hope you can help to resolve this.

**Comment by dpa99c** [comment]
@tusharvikky Try building and running the [example project](https://github.com/dpa99c/cordova-plugin-firebasex-test) and using its FCM API client to send the predefined test messages.

Here's screenshots of it when I send `notification.json` (app build with v6.0.2 of this plugin):

<img width="350" src="https://user-images.githubusercontent.com/2345062/61947748-f49a7400-af9d-11e9-95ed-75f8233b4fdd.png"/>
<img width="350" src="https://user-images.githubusercontent.com/2345062/61947749-f5330a80-af9d-11e9-91c0-63b6fab5676e.png"/>

**Comment by pilz97** [comment]
I have the same problem..
I don't get the onMessageReceived callback, when my app is in foreground but it works when the app is in background and i tap the notification..

**Comment by TIGarupa** [comment]
Exactly as said from @pilz97. I just check this isse and follow the instructions to update the plugin to @6.0.2 but still the same behavior.

![image](https://user-images.githubusercontent.com/29204703/62317966-21a0c800-b471-11e9-8084-1695e292c317.png)
As you can see, I added the setting for ```notification_foreground: 'true'```.

What are I missing here? Can you help us @dpa99c?

**Comment by pilz97** [comment]
@TIGarupa i got the solution!

I just added:
`      <config-file target="AndroidManifest.xml" parent="/manifest/application" >
          <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" />
          <service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService">
            <intent-filter>
              <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
          </service>
          <receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver"/>
          <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" />
          <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id"/>
      </config-file> `

in my `<platform name="android">` section.

Hope that solves the problem for you too :)

**Comment by TIGarupa** [comment]
Thank you @pilz97 this solved for now.
I just think this is just a work around, but for now, can be used.

**Comment by Roman8817** [comment]
@dpa99c I have some issue in ionic4 application.
First of all I appreciate to use your cordova-plugin-firebasex@6.0.7.
I tested using your test app. It is working fully for push notification.
I build ionic4 application using your plugin. So I use typescript wrapper of your plugin.
When app is installed on iOS device first, push notification is working fully.
But after app is closed or changed into background, push notification is not working fully.
In other words, I can see push notification. But "onMessageRecevied" function is not working fully.
I added following function after checking firebase permission.
window['FirebasePlugin'].onMessageReceived(function(message) {
        try{
            console.log("onMessageReceived");
            console.dir(message);
            
        }catch(e){
            // logError("Exception in onMessageReceived callback: "+e.message);
            console.log("Exception in onMessageReceived callback:");
        }

    }, function(error) {
        //logError("Failed receiving FirebasePlugin message: " + error);
        console.log("Failed receiving FirebasePlugin message:");
    });
But I can't see any log data in Xcode console. 
In test project. I think you used same code. 
If you have any idea about this issue, please let me know.
Thanks.

**Comment by nico24github** [comment]
@Roman8817 I have the exact same issue as you.
Did you find a solution to this issue?

**Comment by ramzauchenna** [comment]
Having the exact same issue on android. Any solution to this

**Comment by kartiksolanki** [comment]
Note: on tapping a background notification, if your app is not running, only the data section of the notification message payload will be delivered to onMessageReceived. i.e. the notification title, body, etc. will not. Therefore if you need the properties of the notification message itself (e.g. title & body) to be delivered to onMessageReceived, you must duplicate these in the data section, e.g.:

{
  "name": "my_notification",
  "notification": {
    "body": "Notification body",
    "title": "Notification title"
  },
  "data": {
    "notification_body": "Notification body",
    "notification_title": "Notification title"
  }
}  

Any idea how can i do this? When my app is in background and when i send a notification from FCM, i get my data like this:

background notification {
    "google.delivered_priority": "high",
    "google.sent_time": 1570833258541,
    "google.ttl": 2419200,
    "google.original_priority": "high",
    "messageType": "notification",
    "tap": "background",
    "from": "143972685264",
    "google.message_id": "0:1570833258720050%776720b6776720b6",
    "collapse_key": "com.wearesas.dragonridge"
}

without title and body. How can i get my notification title and body?

**Comment by isaacbatst** [comment]
@pilz97  Thanks man, solved here!

**Comment by iAbhinav** [comment]
> @TIGarupa i got the solution!
> 
> I just added:
> ` <config-file target="AndroidManifest.xml" parent="/manifest/application" > <service android:enabled="true" android:exported="false" android:name="com.google.android.gms.measurement.AppMeasurementService" /> <service android:name="org.apache.cordova.firebase.FirebasePluginMessagingService"> <intent-filter> <action android:name="com.google.firebase.MESSAGING_EVENT"/> </intent-filter> </service> <receiver android:name="org.apache.cordova.firebase.OnNotificationOpenReceiver"/> <meta-data android:name="com.google.firebase.messaging.default_notification_color" android:resource="@color/accent" /> <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id"/> </config-file>`
> 
> in my `<platform name="android">` section.
> 
> Hope that solves the problem for you too :)

This did not work for me.

What I noticed is, that if we call onMessageReceived() the notification is shown only in background, but when in foreground we have to handle the notification.

**Comment by yogeshpatil143** [comment]
Still doesn't work. Please assist me...

**Comment by iAbhinav** [comment]
Let me know how can i assist you. Happy to help.

**Comment by fgarcia5** [comment]
The issue still persist in v9.1.1 and platform Android.
When i receive the push in background and tap this, title and body fields don't appear.
When the push arrive in foreground, both fields are showed.
I have sent notifications from Firebase and my own backend, but the result is the same

**Comment by mohamedHassanKa** [comment]
I have the same issue . when i call it in background i do get the notification and on **onMessageReceived** show me this response 
```
collapse_key: "com.**.**"
from: "599298325333"
google.delivered_priority: "high"
google.message_id: "0:1589550478288659%c0efd0a8c0efd0a8"
google.original_priority: "high"
google.sent_time: 1589550477989
google.ttl: 2419200
messageType: "notification"
tap: "background"
```

but when i call it forground i dont get the notification and **onMessageReceived** show me this response :
```
body: "mm"
collapse_key: "com.proxym.bh"
from: "599298325333"
id: "0:1589550548775009%c0efd0a8c0efd0a8"
messageType: "notification"
sent_time: "1589550548554"
show_notification: "false"
sound: "default"
title: "mm"
ttl: "2419200"
```

any solution please

**Comment by jfrubio** [comment]
Hi.
I'm using cordova-plugin-firebasex 14.0.0, and have the same error.
Push arrive ok in background but in foreground nothing happends, no push is showed and onMessageReceived its not fired. onMessageReceived is only fired if I have the app in foreground and tap on it, then the app opens and I cant work with message. 
¿Any solution?

**Comment by adrianva1983** [comment]
> 
Buenos días, tambien tengo el mismo problema:
Estoy usando cordova-plugin-firebasex 14.0.0 y tengo el mismo error.
El empuje llega bien en segundo plano, pero en primer plano no sucede nada, no se muestra ningún empuje y onMessageReceived no se activa. onMessageReceived solo se activa si tengo la aplicación en primer plano y la toco, luego la aplicación se abre y no puedo trabajar con el mensaje.
¿Alguna solución?
gracias

**Comment by jfrubio** [comment]
Hola [adrianva1983], yo no he encontrado solución. Si encuentro algo te digo, si vieses algo no dejes de avisar. Gracias

**Comment by tolutronics** [comment]
Hello, i think this issue occurs in the recent versions of this plugin.

**Comment by imadkhatib** [comment]
Hello, It occurs in the recent version of plugin("cordova-plugin-firebasex": "^14.1.0")
Please advise.

**Comment by Adityakhandelwal021** [comment]
Hello guys It's fine in the background but  there is issue in getting foreground notification  

 this.firebaseX.onMessageReceived()
      .subscribe(data => console.log(`User opened a notification ${data}`));
      didn't get anything here is console and ad the time of foreground it's not call onMessagerecived because the string is also not print in the console

**Comment by anuskaoo** [comment]
Hola. Mi version del plugin es 16.1.0. Yo tengo el mismo problema en iOS. En segundo plano funciona correctamente tanto en Android como en iOS. En primer plano en ANdroid va bien pero en iOS me da el message como indefinido. ¿Qué puede pasar? Me estoy volviendo loca
Gracias y un saludo.

**Comment by anuskaoo** [comment]
Ayudame @dpa99c por favorrrrrrr. Gracias

**Comment by alejandroldlr** [comment]
Mismo problema firebasex 16.3 IOS en primer plano no recibe los mensajes de data porque no se dispara el evento onMessageReceived
